//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MK6.AutomatedTesting.Runner.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MK6.AutomatedTesting.Runner.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Comment
        ///Key:Value.
        /// </summary>
        internal static string CommentedConfigFile {
            get {
                return ResourceManager.GetString("CommentedConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Key:Value.
        /// </summary>
        internal static string ConfigFileWithLeadingBlankLine {
            get {
                return ResourceManager.GetString("ConfigFileWithLeadingBlankLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key:Value
        ///.
        /// </summary>
        internal static string ConfigFileWithTrailingBlankLine {
            get {
                return ResourceManager.GetString("ConfigFileWithTrailingBlankLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key:Value
        ///Key2:Value.
        /// </summary>
        internal static string ConfigFileWithTwoLines {
            get {
                return ResourceManager.GetString("ConfigFileWithTwoLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EmptyConfigFile {
            get {
                return ResourceManager.GetString("EmptyConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key:Value.
        /// </summary>
        internal static string SingleLine {
            get {
                return ResourceManager.GetString("SingleLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key:http://localhost.
        /// </summary>
        internal static string SingleLineWithColonInValue {
            get {
                return ResourceManager.GetString("SingleLineWithColonInValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Key:Value.
        /// </summary>
        internal static string SingleLineWithLeadingSpaceInKey {
            get {
                return ResourceManager.GetString("SingleLineWithLeadingSpaceInKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key:    Value.
        /// </summary>
        internal static string SingleLineWithLeadingSpaceInValue {
            get {
                return ResourceManager.GetString("SingleLineWithLeadingSpaceInValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key    :Value.
        /// </summary>
        internal static string SingleLineWithTrailingSpaceInKey {
            get {
                return ResourceManager.GetString("SingleLineWithTrailingSpaceInKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key:Value    .
        /// </summary>
        internal static string SingleLineWithTrailingspaceInValue {
            get {
                return ResourceManager.GetString("SingleLineWithTrailingspaceInValue", resourceCulture);
            }
        }
    }
}
